/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasteringClaudeAIRouteImport } from './routes/mastering-Claude-AI'
import { Route as TheClaudeAdvantageRouteImport } from './routes/the-claude-advantage'
import { Route as TheMicrosoftCopilotAdvantageRouteImport } from './routes/the-microsoft-copilot-advantage'
import { Route as TheMicrosoftCopilotAdvantageResourcesRouteImport } from './routes/the-microsoft-copilot-advantage_.resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasteringClaudeAIRoute = MasteringClaudeAIRouteImport.update({
  id: '/mastering-Claude-AI',
  path: '/mastering-Claude-AI',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClaudeAdvantageRoute = TheClaudeAdvantageRouteImport.update({
  id: '/the-claude-advantage',
  path: '/the-claude-advantage',
  getParentRoute: () => rootRouteImport,
} as any)
const TheMicrosoftCopilotAdvantageRoute =
  TheMicrosoftCopilotAdvantageRouteImport.update({
    id: '/the-microsoft-copilot-advantage',
    path: '/the-microsoft-copilot-advantage',
    getParentRoute: () => rootRouteImport,
  } as any)
const TheMicrosoftCopilotAdvantageResourcesRoute =
  TheMicrosoftCopilotAdvantageResourcesRouteImport.update({
    id: '/the-microsoft-copilot-advantage_/resources',
    path: '/the-microsoft-copilot-advantage/resources',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mastering-Claude-AI': typeof MasteringClaudeAIRoute
  '/the-claude-advantage': typeof TheClaudeAdvantageRoute
  '/the-microsoft-copilot-advantage': typeof TheMicrosoftCopilotAdvantageRoute
  '/the-microsoft-copilot-advantage/resources': typeof TheMicrosoftCopilotAdvantageResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mastering-Claude-AI': typeof MasteringClaudeAIRoute
  '/the-claude-advantage': typeof TheClaudeAdvantageRoute
  '/the-microsoft-copilot-advantage': typeof TheMicrosoftCopilotAdvantageRoute
  '/the-microsoft-copilot-advantage/resources': typeof TheMicrosoftCopilotAdvantageResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mastering-Claude-AI': typeof MasteringClaudeAIRoute
  '/the-claude-advantage': typeof TheClaudeAdvantageRoute
  '/the-microsoft-copilot-advantage': typeof TheMicrosoftCopilotAdvantageRoute
  '/the-microsoft-copilot-advantage_/resources': typeof TheMicrosoftCopilotAdvantageResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mastering-Claude-AI'
    | '/the-claude-advantage'
    | '/the-microsoft-copilot-advantage'
    | '/the-microsoft-copilot-advantage/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mastering-Claude-AI'
    | '/the-claude-advantage'
    | '/the-microsoft-copilot-advantage'
    | '/the-microsoft-copilot-advantage/resources'
  id:
    | '__root__'
    | '/'
    | '/mastering-Claude-AI'
    | '/the-claude-advantage'
    | '/the-microsoft-copilot-advantage'
    | '/the-microsoft-copilot-advantage_/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasteringClaudeAIRoute: typeof MasteringClaudeAIRoute
  TheClaudeAdvantageRoute: typeof TheClaudeAdvantageRoute
  TheMicrosoftCopilotAdvantageRoute: typeof TheMicrosoftCopilotAdvantageRoute
  TheMicrosoftCopilotAdvantageResourcesRoute: typeof TheMicrosoftCopilotAdvantageResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mastering-Claude-AI': {
      id: '/mastering-Claude-AI'
      path: '/mastering-Claude-AI'
      fullPath: '/mastering-Claude-AI'
      preLoaderRoute: typeof MasteringClaudeAIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-claude-advantage': {
      id: '/the-claude-advantage'
      path: '/the-claude-advantage'
      fullPath: '/the-claude-advantage'
      preLoaderRoute: typeof TheClaudeAdvantageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-microsoft-copilot-advantage': {
      id: '/the-microsoft-copilot-advantage'
      path: '/the-microsoft-copilot-advantage'
      fullPath: '/the-microsoft-copilot-advantage'
      preLoaderRoute: typeof TheMicrosoftCopilotAdvantageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-microsoft-copilot-advantage_/resources': {
      id: '/the-microsoft-copilot-advantage_/resources'
      path: '/the-microsoft-copilot-advantage/resources'
      fullPath: '/the-microsoft-copilot-advantage/resources'
      preLoaderRoute: typeof TheMicrosoftCopilotAdvantageResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasteringClaudeAIRoute: MasteringClaudeAIRoute,
  TheClaudeAdvantageRoute: TheClaudeAdvantageRoute,
  TheMicrosoftCopilotAdvantageRoute: TheMicrosoftCopilotAdvantageRoute,
  TheMicrosoftCopilotAdvantageResourcesRoute:
    TheMicrosoftCopilotAdvantageResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
